### PR TITLE
Suggest looking at actively maintained akka-js

### PR DESCRIPTION
**Pull request by ktoso**
@andreaTP is actively maintaining the Akka.JS port over here: https://github.com/unicredit/akka.js/
So I thought we might as well link to the more very active one as this repo is still first google result so people might be suprised.

WDYT @adriaanm @phaller ?

### CODE REVIEW

**Comment by ktoso** [comment]
If my wording is off please correct at will :)

**Comment by phaller** [comment]
Looks good to me!

**Comment by ktoso** [comment]
Thanks Philipp! Merging then :)

**Comment by andreaTP** [comment]
YAY! :-)

**Pull request merged**
